### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by YashKumarVerma** [kuldeep-k/procMVC#1]
Is there a documentation ?

**Comment by kuldeep-k** [comment]
No, not yet. It is still very basic and very less of core code. So no need to documentation for now. I add my blog link in README where I tried to describe things little bit.

**Comment by YashKumarVerma** [comment]
One more thing, is the project is working state ?

**Comment by kuldeep-k** [comment]
No, I made this as code proof concept of procedural programming based MVC. I do not think I will convert it into complete working framework with design principles and rich core for actual solutions. But it should still work as simpler solutions I think.
